### PR TITLE
feat: free one of the buffers after generating each layer

### PR DESCRIPTION
**Pull request by keyvank**
This frees 4GiB of GPU memory before giving the control to Neptune.

### CODE REVIEW

**Comment by porcuquine** [comment]
Great. This brings sealing + tree-building time down to 18 minutes (from 20 minutes).

```
➜  rust-fil-nse-gpu git:(do-not-waste) cargo run --release -- -k 8 --num-nodes-window 134217728 --samples 1 --trees
   Compiling rust-fil-nse-gpu v0.1.0 (/home/porcuquine/dev/rust-fil-nse-gpu)
    Finished release [optimized] target(s) in 2.54s
     Running `target/release/bench -k 8 --num-nodes-window 134217728 --samples 1 --trees`
Options: Opts { k: 8, num_nodes_window: 134217728, degree_expander: 384, degree_butterfly: 16, num_expander_layers: 8, num_butterfly_layers: 7, samples: 1, build_trees: true }
Mask: 1707ms
Expander: 116124ms
Butterfly: 1883ms
Combine: 2269ms
Sealer: 1079321ms
```

**Comment by porcuquine** [comment]
@keyvank Can you please rebase this on `master`, so we can merge.

**Comment by porcuquine** [comment]
@keyvank Can you also make this behavior conditional and only free the buffer if we are actually generating trees? We want to be able to optimize for key generation without keys for fastest unsealing.

**Comment by keyvank** [comment]
@porcuquine 

> Can you please rebase this on master, so we can merge.

Done

> Can you also make this behavior conditional and only free the buffer if we are actually generating trees? We want to be able to optimize for key generation without keys for fastest unsealing.

Buffer freeing/reallocation doesn't really have considerable overhead so I don't think this is really necessary, I think it will just make the code complicated.

**Comment by porcuquine** [comment]
This was still showing conflict for some reason, so I squashed it down to one commit and will merge after CI passes.

**Review by porcuquine — APPROVED** [review]

**Pull request merged**
